version: '3.3'

services:
  mysql:
    image: mysql:5.7-debian
    container_name: rolling-db
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: paperdb
      MYSQL_ROOT_HOST: '%' # to allow root connecting from any address.
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '13306:3306'
    networks:
      - rolling-be-db
    restart: always
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  springboot:
    image: springboot-mysql:1.0
    scale: 3
    depends_on:
      - mysql
    ports:
      - '8081-8083:8080'
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://rolling-db:3306/paperdb?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - rolling-be-db
      - rolling-fe-be

  haproxy2:
    image: haproxy:2.4
    container_name: rolling-server
    restart: always
    depends_on:
      - springboot
    ports:
      - '8080:80'
    volumes:
      - /home/ubuntu/rolling2/proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - rolling-be-db
      - rolling-fe-be

  haproxy:
    image: haproxy:2.4
    container_name: rolling-lb
    restart: always
    depends_on:
      - springboot
      - front
      - front_2
      - front_3
    ports:
      - '80:80'
    volumes:
      - /home/ubuntu/rolling2:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - rolling-be-db
      - rolling-fe-be

  front:
    # image: moveho/rolling-fr-1:latest
    image: moveho/new-rolling:v1.0
    container_name: rolling-front
    restart: always
    depends_on:
      - springboot
    ports:
      - '3000:3000'
    networks:
      - rolling-fe-be

  front_2:
    image: moveho/rolling-fr-2:latest
    container_name: rolling-front_2
    restart: always
    depends_on:
      - springboot
    ports:
      - '3001:3000'
    networks:
      - rolling-fe-be

  front_3:
    image: moveho/rolling-fr-3:latest
    container_name: rolling-front_3
    restart: always
    depends_on:
      - springboot
    ports:
      - '3002:3000'
    networks:
      - rolling-fe-be

networks:
  rolling-be-db: {}
  rolling-fe-be: {}

